const http=require('http');const native=http.createServer;
const css='body{margin:0;background:#fffaf4;color:#2d241e;font:16px/1.55 system-ui}.wrap{max-width:900px;margin:auto;padding:0 20px}header{border-bottom:1px solid #eadfd4}.nav{height:68px;display:flex;align-items:center;gap:20px}.brand{font-size:22px;font-weight:900;margin-right:auto}.hero{padding:45px 0 20px}.hero h1{font-size:42px;margin:0}.panel{background:#fff;border:1px solid #eadfd4;border-radius:18px;padding:22px}.field{display:grid;gap:7px;margin:12px 0}.field input,.field select{padding:12px;border:1px solid #ddcfc2;border-radius:12px;font:inherit}.btn{border:0;border-radius:12px;background:#ff6428;color:#fff;padding:12px 16px;font-weight:900}.result{margin-top:16px;padding:16px;background:#fff0e4;border-radius:14px}.big{font-size:30px;font-weight:900}.row{display:flex;gap:12px}.row>*{flex:1}';
function page(t,d,b,s){return '<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+t+'</title><meta name="description" content="'+d+'"><style>'+css+'</style><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3937076958073792" crossorigin="anonymous"></script></head><body><header><div class="wrap nav"><a class="brand" href="/">Ăn Ngon Khỏe</a><a href="/cong-cu">← Công cụ</a></div></header>'+b+s+'</body></html>'}
const routes={
'/cong-cu/luoc-trung':()=>page('Luộc trứng chuẩn','Tính thời gian luộc trứng','<main class="wrap"><section class="hero"><h1>🥚 Luộc trứng chuẩn</h1><p>Chọn độ chín mong muốn.</p></section><section class="panel"><div class="field"><label>Độ chín</label><select id="v"><option value="6">Lòng đào mềm</option><option value="7">Lòng đào vừa</option><option value="9">Chín vừa</option><option value="11">Chín kỹ</option></select></div><button class="btn" onclick="f()">Tính</button><div id="o" class="result"></div></section></main>','<script>function f(){o.innerHTML="<div class=big>"+v.value+" phút</div><p>Tính từ lúc nước sôi nhẹ. Sau đó chuyển trứng sang nước lạnh.</p>"}f()</script>'),
'/cong-cu/nuoc-muoi':()=>page('Tỷ lệ nước muối','Tính lượng muối','<main class="wrap"><section class="hero"><h1>🧂 Tỷ lệ nước muối</h1></section><section class="panel"><div class="field"><label>Nước (ml)</label><input id="w" type="number" value="1000"></div><div class="field"><label>Nồng độ (%)</label><input id="p" type="number" value="2" step=".1"></div><button class="btn" onclick="f()">Tính</button><div id="o" class="result"></div></section></main>','<script>function f(){o.innerHTML="<div class=big>"+((+w.value||0)*(+p.value||0)/100).toFixed(1)+" g muối</div>"}f()</script>'),
'/cong-cu/ty-le-pha':()=>page('Pha theo tỷ lệ','Tính tỷ lệ pha','<main class="wrap"><section class="hero"><h1>🥤 Pha theo tỷ lệ</h1></section><section class="panel"><div class="row"><div class="field"><label>Phần A</label><input id="a" type="number" value="1"></div><div class="field"><label>Phần B</label><input id="b" type="number" value="4"></div></div><div class="field"><label>Tổng lượng</label><input id="t" type="number" value="500"></div><button class="btn" onclick="f()">Tính</button><div id="o" class="result"></div></section></main>','<script>function f(){let x=+a.value||1,y=+b.value||1,z=+t.value||0;o.innerHTML="<b>Phần A:</b> "+(z*x/(x+y)).toFixed(1)+"<br><b>Phần B:</b> "+(z*y/(x+y)).toFixed(1)}f()</script>'),
'/cong-cu/chia-bill':()=>page('Chia hóa đơn','Chia bill thuế tip','<main class="wrap"><section class="hero"><h1>🧾 Chia hóa đơn ăn uống</h1></section><section class="panel"><div class="field"><label>Tiền món ($)</label><input id="s" type="number" value="100"></div><div class="row"><div class="field"><label>Thuế %</label><input id="x" type="number" value="12"></div><div class="field"><label>Tip %</label><input id="y" type="number" value="15"></div><div class="field"><label>Số người</label><input id="n" type="number" value="4"></div></div><button class="btn" onclick="f()">Chia bill</button><div id="o" class="result"></div></section></main>','<script>function f(){let q=+s.value||0,total=q+q*(+x.value||0)/100+q*(+y.value||0)/100,c=Math.max(1,+n.value||1);o.innerHTML="Tổng: <b>$"+total.toFixed(2)+"</b><div class=big>$"+(total/c).toFixed(2)+"/người</div>"}f()</script>')
};
http.createServer=function(handler,...rest){return native.call(http,(req,res)=>{const p=new URL(req.url||'/','http://x').pathname.replace(/\/$/,'')||'/';if(req.method==='GET'&&routes[p]){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});return res.end(routes[p]())}return handler(req,res)},...rest)};